spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dins?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
    username: test
    password: 9999
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true

    properties:
      hibernate:
        show_sql: true